### ISSUE TITLE
Minor issue with the WebApps Style

### ISSUE THREAD

**Issue by maxwoollons** [Killryde/chelsea-fan-page#1]
Good Morning Mr J
I have attached a screenshot of what i see on my end.
Hope this helps you with the development of this applications.
Keep on coding my dude!
[https://ibb.co/tMSz040](https://ibb.co/tMSz040)

Max

**Comment by Killryde** [comment]
Good Afternoon
Mr MAx Woollons

I am aware of this and i have fixed it, but have not updated the project at
this stage

Jaineel

**Comment by maxwoollons** [comment]
Consider this issue closed 👍
